projects:
  crn:
    schemaPath: amplify/backend/api/crn/build/schema.graphql
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/RequestAPI.ts
        docsFilePath: src/graphql
        region: us-west-2
        apiId: null
        maxDepth: 4
extensions:
  amplify:
    version: 3
