/* tslint:disable */
/* eslint-disable */
//  This file was automatically generated and should not be edited.

export type CreateRequestInput = {
  id?: string | null,
  dateOfRequest: string,
  firstName: string,
  lastName: string,
  address?: string | null,
  city: string,
  zipCode?: number | null,
  phone?: string | null,
  email?: string | null,
  spanishOnly?: boolean | null,
  preferredContactTime?: string | null,
  request?: string | null,
  leadSource: LeadSource,
  leadOtherDetails?: string | null,
  resumeHelp?: boolean | null,
  coverLetterHelp?: boolean | null,
  carRepairDetails?: string | null,
  clothingType?: string | null,
  clothingSize?: string | null,
  furnitureType?: string | null,
  housingHelp?: boolean | null,
  needReason: Array< NeedReason | null >,
  needTypes: Array< NeedType | null >,
  status: RequestStatus,
  otherNeeds?: string | null,
  needFulfiller?: string | null,
  dateFulfilled?: string | null,
  followUp?: string | null,
  requestSelfOrOtherInfoId: string,
  requestFoodRequestId?: string | null,
  requestMovingRequestId?: string | null,
  requestHomeRepairTypeId?: string | null,
  requestHouseholdItemsId?: string | null,
};

export enum LeadSource {
  REDEEMERS = "REDEEMERS",
  FAMILY = "FAMILY",
  FRIEND = "FRIEND",
  OTHER = "OTHER",
}


export enum NeedReason {
  COVID = "COVID",
  ILLNESS = "ILLNESS",
  FINANCIAL = "FINANCIAL",
}


export enum NeedType {
  MEALS = "MEALS",
  GROCERIES = "GROCERIES",
  MOVING = "MOVING",
  JOBTRAINING = "JOBTRAINING",
  HOMEREPAIR = "HOMEREPAIR",
  CARREPAIR = "CARREPAIR",
  HOUSING = "HOUSING",
  HOUSEHOLDITEMS = "HOUSEHOLDITEMS",
  CLOTHING = "CLOTHING",
  FURNITURE = "FURNITURE",
  OTHER = "OTHER",
}


export enum RequestStatus {
  NEW = "NEW",
  INPROGRESS = "INPROGRESS",
  FULFILLED = "FULFILLED",
}


export type ModelRequestConditionInput = {
  dateOfRequest?: ModelStringInput | null,
  firstName?: ModelStringInput | null,
  lastName?: ModelStringInput | null,
  address?: ModelStringInput | null,
  city?: ModelStringInput | null,
  zipCode?: ModelIntInput | null,
  phone?: ModelStringInput | null,
  email?: ModelStringInput | null,
  spanishOnly?: ModelBooleanInput | null,
  preferredContactTime?: ModelStringInput | null,
  request?: ModelStringInput | null,
  leadSource?: ModelLeadSourceInput | null,
  leadOtherDetails?: ModelStringInput | null,
  resumeHelp?: ModelBooleanInput | null,
  coverLetterHelp?: ModelBooleanInput | null,
  carRepairDetails?: ModelStringInput | null,
  clothingType?: ModelStringInput | null,
  clothingSize?: ModelStringInput | null,
  furnitureType?: ModelStringInput | null,
  housingHelp?: ModelBooleanInput | null,
  needReason?: ModelNeedReasonListInput | null,
  needTypes?: ModelNeedTypeListInput | null,
  status?: ModelRequestStatusInput | null,
  otherNeeds?: ModelStringInput | null,
  needFulfiller?: ModelStringInput | null,
  dateFulfilled?: ModelStringInput | null,
  followUp?: ModelStringInput | null,
  and?: Array< ModelRequestConditionInput | null > | null,
  or?: Array< ModelRequestConditionInput | null > | null,
  not?: ModelRequestConditionInput | null,
};

export type ModelStringInput = {
  ne?: string | null,
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  contains?: string | null,
  notContains?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
  size?: ModelSizeInput | null,
};

export enum ModelAttributeTypes {
  binary = "binary",
  binarySet = "binarySet",
  bool = "bool",
  list = "list",
  map = "map",
  number = "number",
  numberSet = "numberSet",
  string = "string",
  stringSet = "stringSet",
  _null = "_null",
}


export type ModelSizeInput = {
  ne?: number | null,
  eq?: number | null,
  le?: number | null,
  lt?: number | null,
  ge?: number | null,
  gt?: number | null,
  between?: Array< number | null > | null,
};

export type ModelIntInput = {
  ne?: number | null,
  eq?: number | null,
  le?: number | null,
  lt?: number | null,
  ge?: number | null,
  gt?: number | null,
  between?: Array< number | null > | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
};

export type ModelBooleanInput = {
  ne?: boolean | null,
  eq?: boolean | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
};

export type ModelLeadSourceInput = {
  eq?: LeadSource | null,
  ne?: LeadSource | null,
};

export type ModelNeedReasonListInput = {
  eq?: Array< NeedReason | null > | null,
  ne?: Array< NeedReason | null > | null,
  contains?: NeedReason | null,
  notContains?: NeedReason | null,
};

export type ModelNeedTypeListInput = {
  eq?: Array< NeedType | null > | null,
  ne?: Array< NeedType | null > | null,
  contains?: NeedType | null,
  notContains?: NeedType | null,
};

export type ModelRequestStatusInput = {
  eq?: RequestStatus | null,
  ne?: RequestStatus | null,
};

export type Request = {
  __typename: "Request",
  id: string,
  dateOfRequest: string,
  firstName: string,
  lastName: string,
  address?: string | null,
  city: string,
  zipCode?: number | null,
  phone?: string | null,
  email?: string | null,
  spanishOnly?: boolean | null,
  preferredContactTime?: string | null,
  request?: string | null,
  leadSource: LeadSource,
  leadOtherDetails?: string | null,
  selfOrOtherInfo: SelfOrOtherInfo,
  foodRequest?: FoodInfo | null,
  movingRequest?: MovingInfo | null,
  resumeHelp?: boolean | null,
  coverLetterHelp?: boolean | null,
  carRepairDetails?: string | null,
  homeRepairType?: HomeRepairType | null,
  clothingType?: string | null,
  clothingSize?: string | null,
  furnitureType?: string | null,
  housingHelp?: boolean | null,
  householdItems?: HouseholdItems | null,
  needReason: Array< NeedReason | null >,
  needTypes: Array< NeedType | null >,
  status: RequestStatus,
  note?: ModelNoteTypeConnection | null,
  otherNeeds?: string | null,
  needFulfiller?: string | null,
  dateFulfilled?: string | null,
  followUp?: string | null,
  createdAt: string,
  updatedAt: string,
};

export type SelfOrOtherInfo = {
  __typename: "SelfOrOtherInfo",
  id: string,
  forSelf?: boolean | null,
  usedOtherResources?: boolean | null,
  otherResources?: string | null,
  requestFor?: string | null,
  requestIsKnown?: boolean | null,
  createdAt: string,
  updatedAt: string,
};

export type FoodInfo = {
  __typename: "FoodInfo",
  id: string,
  familyMembers?: number | null,
  children?: string | null,
  haveAllergies?: boolean | null,
  allergies?: string | null,
  milk?: boolean | null,
  eggs?: boolean | null,
  bread?: boolean | null,
  butter?: boolean | null,
  tortillas?: boolean | null,
  rice?: boolean | null,
  beans?: boolean | null,
  cheese?: boolean | null,
  beef?: boolean | null,
  hotdogs?: boolean | null,
  lunchMeat?: boolean | null,
  fruit?: boolean | null,
  peanutButter?: boolean | null,
  jelly?: boolean | null,
  createdAt: string,
  updatedAt: string,
};

export type MovingInfo = {
  __typename: "MovingInfo",
  id: string,
  items?: string | null,
  haveTransportation?: boolean | null,
  steepDriveway?: boolean | null,
  stairs?: boolean | null,
  unpavedRoad?: boolean | null,
  other?: boolean | null,
  otherDetails?: string | null,
  liabilityAck?: boolean | null,
  createdAt: string,
  updatedAt: string,
};

export type HomeRepairType = {
  __typename: "HomeRepairType",
  id: string,
  plumbing?: boolean | null,
  electrical?: boolean | null,
  painting?: boolean | null,
  yardwork?: boolean | null,
  other?: boolean | null,
  details?: string | null,
  createdAt: string,
  updatedAt: string,
};

export type HouseholdItems = {
  __typename: "HouseholdItems",
  id: string,
  shampoo?: boolean | null,
  bathSoap?: boolean | null,
  toothpaste?: boolean | null,
  toothbrush?: boolean | null,
  deodorant?: boolean | null,
  toiletPaper?: boolean | null,
  handSoap?: boolean | null,
  sanitaryPads?: boolean | null,
  tampons?: boolean | null,
  bleach?: boolean | null,
  lysolSpray?: boolean | null,
  lysolWipes?: boolean | null,
  dishsoap?: boolean | null,
  sponges?: boolean | null,
  pinesol?: boolean | null,
  createdAt: string,
  updatedAt: string,
};

export type ModelNoteTypeConnection = {
  __typename: "ModelNoteTypeConnection",
  items:  Array<NoteType | null >,
  nextToken?: string | null,
};

export type NoteType = {
  __typename: "NoteType",
  id: string,
  requestID: string,
  dateCreated: string,
  author: string,
  content: string,
  createdAt: string,
  updatedAt: string,
};

export type UpdateRequestInput = {
  id: string,
  dateOfRequest?: string | null,
  firstName?: string | null,
  lastName?: string | null,
  address?: string | null,
  city?: string | null,
  zipCode?: number | null,
  phone?: string | null,
  email?: string | null,
  spanishOnly?: boolean | null,
  preferredContactTime?: string | null,
  request?: string | null,
  leadSource?: LeadSource | null,
  leadOtherDetails?: string | null,
  resumeHelp?: boolean | null,
  coverLetterHelp?: boolean | null,
  carRepairDetails?: string | null,
  clothingType?: string | null,
  clothingSize?: string | null,
  furnitureType?: string | null,
  housingHelp?: boolean | null,
  needReason?: Array< NeedReason | null > | null,
  needTypes?: Array< NeedType | null > | null,
  status?: RequestStatus | null,
  otherNeeds?: string | null,
  needFulfiller?: string | null,
  dateFulfilled?: string | null,
  followUp?: string | null,
  requestSelfOrOtherInfoId?: string | null,
  requestFoodRequestId?: string | null,
  requestMovingRequestId?: string | null,
  requestHomeRepairTypeId?: string | null,
  requestHouseholdItemsId?: string | null,
};

export type DeleteRequestInput = {
  id: string,
};

export type CreateNoteTypeInput = {
  id?: string | null,
  requestID: string,
  dateCreated: string,
  author: string,
  content: string,
};

export type ModelNoteTypeConditionInput = {
  requestID?: ModelIDInput | null,
  dateCreated?: ModelStringInput | null,
  author?: ModelStringInput | null,
  content?: ModelStringInput | null,
  and?: Array< ModelNoteTypeConditionInput | null > | null,
  or?: Array< ModelNoteTypeConditionInput | null > | null,
  not?: ModelNoteTypeConditionInput | null,
};

export type ModelIDInput = {
  ne?: string | null,
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  contains?: string | null,
  notContains?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
  attributeExists?: boolean | null,
  attributeType?: ModelAttributeTypes | null,
  size?: ModelSizeInput | null,
};

export type UpdateNoteTypeInput = {
  id: string,
  requestID?: string | null,
  dateCreated?: string | null,
  author?: string | null,
  content?: string | null,
};

export type DeleteNoteTypeInput = {
  id: string,
};

export type CreateSelfOrOtherInfoInput = {
  id?: string | null,
  forSelf?: boolean | null,
  usedOtherResources?: boolean | null,
  otherResources?: string | null,
  requestFor?: string | null,
  requestIsKnown?: boolean | null,
};

export type ModelSelfOrOtherInfoConditionInput = {
  forSelf?: ModelBooleanInput | null,
  usedOtherResources?: ModelBooleanInput | null,
  otherResources?: ModelStringInput | null,
  requestFor?: ModelStringInput | null,
  requestIsKnown?: ModelBooleanInput | null,
  and?: Array< ModelSelfOrOtherInfoConditionInput | null > | null,
  or?: Array< ModelSelfOrOtherInfoConditionInput | null > | null,
  not?: ModelSelfOrOtherInfoConditionInput | null,
};

export type UpdateSelfOrOtherInfoInput = {
  id: string,
  forSelf?: boolean | null,
  usedOtherResources?: boolean | null,
  otherResources?: string | null,
  requestFor?: string | null,
  requestIsKnown?: boolean | null,
};

export type DeleteSelfOrOtherInfoInput = {
  id: string,
};

export type CreateHouseholdItemsInput = {
  id?: string | null,
  shampoo?: boolean | null,
  bathSoap?: boolean | null,
  toothpaste?: boolean | null,
  toothbrush?: boolean | null,
  deodorant?: boolean | null,
  toiletPaper?: boolean | null,
  handSoap?: boolean | null,
  sanitaryPads?: boolean | null,
  tampons?: boolean | null,
  bleach?: boolean | null,
  lysolSpray?: boolean | null,
  lysolWipes?: boolean | null,
  dishsoap?: boolean | null,
  sponges?: boolean | null,
  pinesol?: boolean | null,
};

export type ModelHouseholdItemsConditionInput = {
  shampoo?: ModelBooleanInput | null,
  bathSoap?: ModelBooleanInput | null,
  toothpaste?: ModelBooleanInput | null,
  toothbrush?: ModelBooleanInput | null,
  deodorant?: ModelBooleanInput | null,
  toiletPaper?: ModelBooleanInput | null,
  handSoap?: ModelBooleanInput | null,
  sanitaryPads?: ModelBooleanInput | null,
  tampons?: ModelBooleanInput | null,
  bleach?: ModelBooleanInput | null,
  lysolSpray?: ModelBooleanInput | null,
  lysolWipes?: ModelBooleanInput | null,
  dishsoap?: ModelBooleanInput | null,
  sponges?: ModelBooleanInput | null,
  pinesol?: ModelBooleanInput | null,
  and?: Array< ModelHouseholdItemsConditionInput | null > | null,
  or?: Array< ModelHouseholdItemsConditionInput | null > | null,
  not?: ModelHouseholdItemsConditionInput | null,
};

export type UpdateHouseholdItemsInput = {
  id: string,
  shampoo?: boolean | null,
  bathSoap?: boolean | null,
  toothpaste?: boolean | null,
  toothbrush?: boolean | null,
  deodorant?: boolean | null,
  toiletPaper?: boolean | null,
  handSoap?: boolean | null,
  sanitaryPads?: boolean | null,
  tampons?: boolean | null,
  bleach?: boolean | null,
  lysolSpray?: boolean | null,
  lysolWipes?: boolean | null,
  dishsoap?: boolean | null,
  sponges?: boolean | null,
  pinesol?: boolean | null,
};

export type DeleteHouseholdItemsInput = {
  id: string,
};

export type CreateFoodInfoInput = {
  id?: string | null,
  familyMembers?: number | null,
  children?: string | null,
  haveAllergies?: boolean | null,
  allergies?: string | null,
  milk?: boolean | null,
  eggs?: boolean | null,
  bread?: boolean | null,
  butter?: boolean | null,
  tortillas?: boolean | null,
  rice?: boolean | null,
  beans?: boolean | null,
  cheese?: boolean | null,
  beef?: boolean | null,
  hotdogs?: boolean | null,
  lunchMeat?: boolean | null,
  fruit?: boolean | null,
  peanutButter?: boolean | null,
  jelly?: boolean | null,
};

export type ModelFoodInfoConditionInput = {
  familyMembers?: ModelIntInput | null,
  children?: ModelStringInput | null,
  haveAllergies?: ModelBooleanInput | null,
  allergies?: ModelStringInput | null,
  milk?: ModelBooleanInput | null,
  eggs?: ModelBooleanInput | null,
  bread?: ModelBooleanInput | null,
  butter?: ModelBooleanInput | null,
  tortillas?: ModelBooleanInput | null,
  rice?: ModelBooleanInput | null,
  beans?: ModelBooleanInput | null,
  cheese?: ModelBooleanInput | null,
  beef?: ModelBooleanInput | null,
  hotdogs?: ModelBooleanInput | null,
  lunchMeat?: ModelBooleanInput | null,
  fruit?: ModelBooleanInput | null,
  peanutButter?: ModelBooleanInput | null,
  jelly?: ModelBooleanInput | null,
  and?: Array< ModelFoodInfoConditionInput | null > | null,
  or?: Array< ModelFoodInfoConditionInput | null > | null,
  not?: ModelFoodInfoConditionInput | null,
};

export type UpdateFoodInfoInput = {
  id: string,
  familyMembers?: number | null,
  children?: string | null,
  haveAllergies?: boolean | null,
  allergies?: string | null,
  milk?: boolean | null,
  eggs?: boolean | null,
  bread?: boolean | null,
  butter?: boolean | null,
  tortillas?: boolean | null,
  rice?: boolean | null,
  beans?: boolean | null,
  cheese?: boolean | null,
  beef?: boolean | null,
  hotdogs?: boolean | null,
  lunchMeat?: boolean | null,
  fruit?: boolean | null,
  peanutButter?: boolean | null,
  jelly?: boolean | null,
};

export type DeleteFoodInfoInput = {
  id: string,
};

export type CreateMovingInfoInput = {
  id?: string | null,
  items?: string | null,
  haveTransportation?: boolean | null,
  steepDriveway?: boolean | null,
  stairs?: boolean | null,
  unpavedRoad?: boolean | null,
  other?: boolean | null,
  otherDetails?: string | null,
  liabilityAck?: boolean | null,
};

export type ModelMovingInfoConditionInput = {
  items?: ModelStringInput | null,
  haveTransportation?: ModelBooleanInput | null,
  steepDriveway?: ModelBooleanInput | null,
  stairs?: ModelBooleanInput | null,
  unpavedRoad?: ModelBooleanInput | null,
  other?: ModelBooleanInput | null,
  otherDetails?: ModelStringInput | null,
  liabilityAck?: ModelBooleanInput | null,
  and?: Array< ModelMovingInfoConditionInput | null > | null,
  or?: Array< ModelMovingInfoConditionInput | null > | null,
  not?: ModelMovingInfoConditionInput | null,
};

export type UpdateMovingInfoInput = {
  id: string,
  items?: string | null,
  haveTransportation?: boolean | null,
  steepDriveway?: boolean | null,
  stairs?: boolean | null,
  unpavedRoad?: boolean | null,
  other?: boolean | null,
  otherDetails?: string | null,
  liabilityAck?: boolean | null,
};

export type DeleteMovingInfoInput = {
  id: string,
};

export type CreateHomeRepairTypeInput = {
  id?: string | null,
  plumbing?: boolean | null,
  electrical?: boolean | null,
  painting?: boolean | null,
  yardwork?: boolean | null,
  other?: boolean | null,
  details?: string | null,
};

export type ModelHomeRepairTypeConditionInput = {
  plumbing?: ModelBooleanInput | null,
  electrical?: ModelBooleanInput | null,
  painting?: ModelBooleanInput | null,
  yardwork?: ModelBooleanInput | null,
  other?: ModelBooleanInput | null,
  details?: ModelStringInput | null,
  and?: Array< ModelHomeRepairTypeConditionInput | null > | null,
  or?: Array< ModelHomeRepairTypeConditionInput | null > | null,
  not?: ModelHomeRepairTypeConditionInput | null,
};

export type UpdateHomeRepairTypeInput = {
  id: string,
  plumbing?: boolean | null,
  electrical?: boolean | null,
  painting?: boolean | null,
  yardwork?: boolean | null,
  other?: boolean | null,
  details?: string | null,
};

export type DeleteHomeRepairTypeInput = {
  id: string,
};

export type ModelRequestFilterInput = {
  id?: ModelIDInput | null,
  dateOfRequest?: ModelStringInput | null,
  firstName?: ModelStringInput | null,
  lastName?: ModelStringInput | null,
  address?: ModelStringInput | null,
  city?: ModelStringInput | null,
  zipCode?: ModelIntInput | null,
  phone?: ModelStringInput | null,
  email?: ModelStringInput | null,
  spanishOnly?: ModelBooleanInput | null,
  preferredContactTime?: ModelStringInput | null,
  request?: ModelStringInput | null,
  leadSource?: ModelLeadSourceInput | null,
  leadOtherDetails?: ModelStringInput | null,
  resumeHelp?: ModelBooleanInput | null,
  coverLetterHelp?: ModelBooleanInput | null,
  carRepairDetails?: ModelStringInput | null,
  clothingType?: ModelStringInput | null,
  clothingSize?: ModelStringInput | null,
  furnitureType?: ModelStringInput | null,
  housingHelp?: ModelBooleanInput | null,
  needReason?: ModelNeedReasonListInput | null,
  needTypes?: ModelNeedTypeListInput | null,
  status?: ModelRequestStatusInput | null,
  otherNeeds?: ModelStringInput | null,
  needFulfiller?: ModelStringInput | null,
  dateFulfilled?: ModelStringInput | null,
  followUp?: ModelStringInput | null,
  and?: Array< ModelRequestFilterInput | null > | null,
  or?: Array< ModelRequestFilterInput | null > | null,
  not?: ModelRequestFilterInput | null,
};

export type ModelRequestConnection = {
  __typename: "ModelRequestConnection",
  items:  Array<Request | null >,
  nextToken?: string | null,
};

export type ModelNoteTypeFilterInput = {
  id?: ModelIDInput | null,
  requestID?: ModelIDInput | null,
  dateCreated?: ModelStringInput | null,
  author?: ModelStringInput | null,
  content?: ModelStringInput | null,
  and?: Array< ModelNoteTypeFilterInput | null > | null,
  or?: Array< ModelNoteTypeFilterInput | null > | null,
  not?: ModelNoteTypeFilterInput | null,
};

export type ModelSelfOrOtherInfoFilterInput = {
  forSelf?: ModelBooleanInput | null,
  usedOtherResources?: ModelBooleanInput | null,
  otherResources?: ModelStringInput | null,
  requestFor?: ModelStringInput | null,
  requestIsKnown?: ModelBooleanInput | null,
  and?: Array< ModelSelfOrOtherInfoFilterInput | null > | null,
  or?: Array< ModelSelfOrOtherInfoFilterInput | null > | null,
  not?: ModelSelfOrOtherInfoFilterInput | null,
};

export type ModelSelfOrOtherInfoConnection = {
  __typename: "ModelSelfOrOtherInfoConnection",
  items:  Array<SelfOrOtherInfo | null >,
  nextToken?: string | null,
};

export type ModelHouseholdItemsFilterInput = {
  shampoo?: ModelBooleanInput | null,
  bathSoap?: ModelBooleanInput | null,
  toothpaste?: ModelBooleanInput | null,
  toothbrush?: ModelBooleanInput | null,
  deodorant?: ModelBooleanInput | null,
  toiletPaper?: ModelBooleanInput | null,
  handSoap?: ModelBooleanInput | null,
  sanitaryPads?: ModelBooleanInput | null,
  tampons?: ModelBooleanInput | null,
  bleach?: ModelBooleanInput | null,
  lysolSpray?: ModelBooleanInput | null,
  lysolWipes?: ModelBooleanInput | null,
  dishsoap?: ModelBooleanInput | null,
  sponges?: ModelBooleanInput | null,
  pinesol?: ModelBooleanInput | null,
  and?: Array< ModelHouseholdItemsFilterInput | null > | null,
  or?: Array< ModelHouseholdItemsFilterInput | null > | null,
  not?: ModelHouseholdItemsFilterInput | null,
};

export type ModelHouseholdItemsConnection = {
  __typename: "ModelHouseholdItemsConnection",
  items:  Array<HouseholdItems | null >,
  nextToken?: string | null,
};

export type ModelFoodInfoFilterInput = {
  familyMembers?: ModelIntInput | null,
  children?: ModelStringInput | null,
  haveAllergies?: ModelBooleanInput | null,
  allergies?: ModelStringInput | null,
  milk?: ModelBooleanInput | null,
  eggs?: ModelBooleanInput | null,
  bread?: ModelBooleanInput | null,
  butter?: ModelBooleanInput | null,
  tortillas?: ModelBooleanInput | null,
  rice?: ModelBooleanInput | null,
  beans?: ModelBooleanInput | null,
  cheese?: ModelBooleanInput | null,
  beef?: ModelBooleanInput | null,
  hotdogs?: ModelBooleanInput | null,
  lunchMeat?: ModelBooleanInput | null,
  fruit?: ModelBooleanInput | null,
  peanutButter?: ModelBooleanInput | null,
  jelly?: ModelBooleanInput | null,
  and?: Array< ModelFoodInfoFilterInput | null > | null,
  or?: Array< ModelFoodInfoFilterInput | null > | null,
  not?: ModelFoodInfoFilterInput | null,
};

export type ModelFoodInfoConnection = {
  __typename: "ModelFoodInfoConnection",
  items:  Array<FoodInfo | null >,
  nextToken?: string | null,
};

export type ModelMovingInfoFilterInput = {
  items?: ModelStringInput | null,
  haveTransportation?: ModelBooleanInput | null,
  steepDriveway?: ModelBooleanInput | null,
  stairs?: ModelBooleanInput | null,
  unpavedRoad?: ModelBooleanInput | null,
  other?: ModelBooleanInput | null,
  otherDetails?: ModelStringInput | null,
  liabilityAck?: ModelBooleanInput | null,
  and?: Array< ModelMovingInfoFilterInput | null > | null,
  or?: Array< ModelMovingInfoFilterInput | null > | null,
  not?: ModelMovingInfoFilterInput | null,
};

export type ModelMovingInfoConnection = {
  __typename: "ModelMovingInfoConnection",
  items:  Array<MovingInfo | null >,
  nextToken?: string | null,
};

export type ModelHomeRepairTypeFilterInput = {
  plumbing?: ModelBooleanInput | null,
  electrical?: ModelBooleanInput | null,
  painting?: ModelBooleanInput | null,
  yardwork?: ModelBooleanInput | null,
  other?: ModelBooleanInput | null,
  details?: ModelStringInput | null,
  and?: Array< ModelHomeRepairTypeFilterInput | null > | null,
  or?: Array< ModelHomeRepairTypeFilterInput | null > | null,
  not?: ModelHomeRepairTypeFilterInput | null,
};

export type ModelHomeRepairTypeConnection = {
  __typename: "ModelHomeRepairTypeConnection",
  items:  Array<HomeRepairType | null >,
  nextToken?: string | null,
};

export type CreateRequestMutationVariables = {
  input: CreateRequestInput,
  condition?: ModelRequestConditionInput | null,
};

export type CreateRequestMutation = {
  createRequest?:  {
    __typename: "Request",
    id: string,
    dateOfRequest: string,
    firstName: string,
    lastName: string,
    address?: string | null,
    city: string,
    zipCode?: number | null,
    phone?: string | null,
    email?: string | null,
    spanishOnly?: boolean | null,
    preferredContactTime?: string | null,
    request?: string | null,
    leadSource: LeadSource,
    leadOtherDetails?: string | null,
    selfOrOtherInfo:  {
      __typename: "SelfOrOtherInfo",
      id: string,
      forSelf?: boolean | null,
      usedOtherResources?: boolean | null,
      otherResources?: string | null,
      requestFor?: string | null,
      requestIsKnown?: boolean | null,
      createdAt: string,
      updatedAt: string,
    },
    foodRequest?:  {
      __typename: "FoodInfo",
      id: string,
      familyMembers?: number | null,
      children?: string | null,
      haveAllergies?: boolean | null,
      allergies?: string | null,
      milk?: boolean | null,
      eggs?: boolean | null,
      bread?: boolean | null,
      butter?: boolean | null,
      tortillas?: boolean | null,
      rice?: boolean | null,
      beans?: boolean | null,
      cheese?: boolean | null,
      beef?: boolean | null,
      hotdogs?: boolean | null,
      lunchMeat?: boolean | null,
      fruit?: boolean | null,
      peanutButter?: boolean | null,
      jelly?: boolean | null,
      createdAt: string,
      updatedAt: string,
    } | null,
    movingRequest?:  {
      __typename: "MovingInfo",
      id: string,
      items?: string | null,
      haveTransportation?: boolean | null,
      steepDriveway?: boolean | null,
      stairs?: boolean | null,
      unpavedRoad?: boolean | null,
      other?: boolean | null,
      otherDetails?: string | null,
      liabilityAck?: boolean | null,
      createdAt: string,
      updatedAt: string,
    } | null,
    resumeHelp?: boolean | null,
    coverLetterHelp?: boolean | null,
    carRepairDetails?: string | null,
    homeRepairType?:  {
      __typename: "HomeRepairType",
      id: string,
      plumbing?: boolean | null,
      electrical?: boolean | null,
      painting?: boolean | null,
      yardwork?: boolean | null,
      other?: boolean | null,
      details?: string | null,
      createdAt: string,
      updatedAt: string,
    } | null,
    clothingType?: string | null,
    clothingSize?: string | null,
    furnitureType?: string | null,
    housingHelp?: boolean | null,
    householdItems?:  {
      __typename: "HouseholdItems",
      id: string,
      shampoo?: boolean | null,
      bathSoap?: boolean | null,
      toothpaste?: boolean | null,
      toothbrush?: boolean | null,
      deodorant?: boolean | null,
      toiletPaper?: boolean | null,
      handSoap?: boolean | null,
      sanitaryPads?: boolean | null,
      tampons?: boolean | null,
      bleach?: boolean | null,
      lysolSpray?: boolean | null,
      lysolWipes?: boolean | null,
      dishsoap?: boolean | null,
      sponges?: boolean | null,
      pinesol?: boolean | null,
      createdAt: string,
      updatedAt: string,
    } | null,
    needReason: Array< NeedReason | null >,
    needTypes: Array< NeedType | null >,
    status: RequestStatus,
    note?:  {
      __typename: "ModelNoteTypeConnection",
      items:  Array< {
        __typename: "NoteType",
        id: string,
        requestID: string,
        dateCreated: string,
        author: string,
        content: string,
        createdAt: string,
        updatedAt: string,
      } | null >,
      nextToken?: string | null,
    } | null,
    otherNeeds?: string | null,
    needFulfiller?: string | null,
    dateFulfilled?: string | null,
    followUp?: string | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type UpdateRequestMutationVariables = {
  input: UpdateRequestInput,
  condition?: ModelRequestConditionInput | null,
};

export type UpdateRequestMutation = {
  updateRequest?:  {
    __typename: "Request",
    id: string,
    dateOfRequest: string,
    firstName: string,
    lastName: string,
    address?: string | null,
    city: string,
    zipCode?: number | null,
    phone?: string | null,
    email?: string | null,
    spanishOnly?: boolean | null,
    preferredContactTime?: string | null,
    request?: string | null,
    leadSource: LeadSource,
    leadOtherDetails?: string | null,
    selfOrOtherInfo:  {
      __typename: "SelfOrOtherInfo",
      id: string,
      forSelf?: boolean | null,
      usedOtherResources?: boolean | null,
      otherResources?: string | null,
      requestFor?: string | null,
      requestIsKnown?: boolean | null,
      createdAt: string,
      updatedAt: string,
    },
    foodRequest?:  {
      __typename: "FoodInfo",
      id: string,
      familyMembers?: number | null,
      children?: string | null,
      haveAllergies?: boolean | null,
      allergies?: string | null,
      milk?: boolean | null,
      eggs?: boolean | null,
      bread?: boolean | null,
      butter?: boolean | null,
      tortillas?: boolean | null,
      rice?: boolean | null,
      beans?: boolean | null,
      cheese?: boolean | null,
      beef?: boolean | null,
      hotdogs?: boolean | null,
      lunchMeat?: boolean | null,
      fruit?: boolean | null,
      peanutButter?: boolean | null,
      jelly?: boolean | null,
      createdAt: string,
      updatedAt: string,
    } | null,
    movingRequest?:  {
      __typename: "MovingInfo",
      id: string,
      items?: string | null,
      haveTransportation?: boolean | null,
      steepDriveway?: boolean | null,
      stairs?: boolean | null,
      unpavedRoad?: boolean | null,
      other?: boolean | null,
      otherDetails?: string | null,
      liabilityAck?: boolean | null,
      createdAt: string,
      updatedAt: string,
    } | null,
    resumeHelp?: boolean | null,
    coverLetterHelp?: boolean | null,
    carRepairDetails?: string | null,
    homeRepairType?:  {
      __typename: "HomeRepairType",
      id: string,
      plumbing?: boolean | null,
      electrical?: boolean | null,
      painting?: boolean | null,
      yardwork?: boolean | null,
      other?: boolean | null,
      details?: string | null,
      createdAt: string,
      updatedAt: string,
    } | null,
    clothingType?: string | null,
    clothingSize?: string | null,
    furnitureType?: string | null,
    housingHelp?: boolean | null,
    householdItems?:  {
      __typename: "HouseholdItems",
      id: string,
      shampoo?: boolean | null,
      bathSoap?: boolean | null,
      toothpaste?: boolean | null,
      toothbrush?: boolean | null,
      deodorant?: boolean | null,
      toiletPaper?: boolean | null,
      handSoap?: boolean | null,
      sanitaryPads?: boolean | null,
      tampons?: boolean | null,
      bleach?: boolean | null,
      lysolSpray?: boolean | null,
      lysolWipes?: boolean | null,
      dishsoap?: boolean | null,
      sponges?: boolean | null,
      pinesol?: boolean | null,
      createdAt: string,
      updatedAt: string,
    } | null,
    needReason: Array< NeedReason | null >,
    needTypes: Array< NeedType | null >,
    status: RequestStatus,
    note?:  {
      __typename: "ModelNoteTypeConnection",
      items:  Array< {
        __typename: "NoteType",
        id: string,
        requestID: string,
        dateCreated: string,
        author: string,
        content: string,
        createdAt: string,
        updatedAt: string,
      } | null >,
      nextToken?: string | null,
    } | null,
    otherNeeds?: string | null,
    needFulfiller?: string | null,
    dateFulfilled?: string | null,
    followUp?: string | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type DeleteRequestMutationVariables = {
  input: DeleteRequestInput,
  condition?: ModelRequestConditionInput | null,
};

export type DeleteRequestMutation = {
  deleteRequest?:  {
    __typename: "Request",
    id: string,
    dateOfRequest: string,
    firstName: string,
    lastName: string,
    address?: string | null,
    city: string,
    zipCode?: number | null,
    phone?: string | null,
    email?: string | null,
    spanishOnly?: boolean | null,
    preferredContactTime?: string | null,
    request?: string | null,
    leadSource: LeadSource,
    leadOtherDetails?: string | null,
    selfOrOtherInfo:  {
      __typename: "SelfOrOtherInfo",
      id: string,
      forSelf?: boolean | null,
      usedOtherResources?: boolean | null,
      otherResources?: string | null,
      requestFor?: string | null,
      requestIsKnown?: boolean | null,
      createdAt: string,
      updatedAt: string,
    },
    foodRequest?:  {
      __typename: "FoodInfo",
      id: string,
      familyMembers?: number | null,
      children?: string | null,
      haveAllergies?: boolean | null,
      allergies?: string | null,
      milk?: boolean | null,
      eggs?: boolean | null,
      bread?: boolean | null,
      butter?: boolean | null,
      tortillas?: boolean | null,
      rice?: boolean | null,
      beans?: boolean | null,
      cheese?: boolean | null,
      beef?: boolean | null,
      hotdogs?: boolean | null,
      lunchMeat?: boolean | null,
      fruit?: boolean | null,
      peanutButter?: boolean | null,
      jelly?: boolean | null,
      createdAt: string,
      updatedAt: string,
    } | null,
    movingRequest?:  {
      __typename: "MovingInfo",
      id: string,
      items?: string | null,
      haveTransportation?: boolean | null,
      steepDriveway?: boolean | null,
      stairs?: boolean | null,
      unpavedRoad?: boolean | null,
      other?: boolean | null,
      otherDetails?: string | null,
      liabilityAck?: boolean | null,
      createdAt: string,
      updatedAt: string,
    } | null,
    resumeHelp?: boolean | null,
    coverLetterHelp?: boolean | null,
    carRepairDetails?: string | null,
    homeRepairType?:  {
      __typename: "HomeRepairType",
      id: string,
      plumbing?: boolean | null,
      electrical?: boolean | null,
      painting?: boolean | null,
      yardwork?: boolean | null,
      other?: boolean | null,
      details?: string | null,
      createdAt: string,
      updatedAt: string,
    } | null,
    clothingType?: string | null,
    clothingSize?: string | null,
    furnitureType?: string | null,
    housingHelp?: boolean | null,
    householdItems?:  {
      __typename: "HouseholdItems",
      id: string,
      shampoo?: boolean | null,
      bathSoap?: boolean | null,
      toothpaste?: boolean | null,
      toothbrush?: boolean | null,
      deodorant?: boolean | null,
      toiletPaper?: boolean | null,
      handSoap?: boolean | null,
      sanitaryPads?: boolean | null,
      tampons?: boolean | null,
      bleach?: boolean | null,
      lysolSpray?: boolean | null,
      lysolWipes?: boolean | null,
      dishsoap?: boolean | null,
      sponges?: boolean | null,
      pinesol?: boolean | null,
      createdAt: string,
      updatedAt: string,
    } | null,
    needReason: Array< NeedReason | null >,
    needTypes: Array< NeedType | null >,
    status: RequestStatus,
    note?:  {
      __typename: "ModelNoteTypeConnection",
      items:  Array< {
        __typename: "NoteType",
        id: string,
        requestID: string,
        dateCreated: string,
        author: string,
        content: string,
        createdAt: string,
        updatedAt: string,
      } | null >,
      nextToken?: string | null,
    } | null,
    otherNeeds?: string | null,
    needFulfiller?: string | null,
    dateFulfilled?: string | null,
    followUp?: string | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type CreateNoteTypeMutationVariables = {
  input: CreateNoteTypeInput,
  condition?: ModelNoteTypeConditionInput | null,
};

export type CreateNoteTypeMutation = {
  createNoteType?:  {
    __typename: "NoteType",
    id: string,
    requestID: string,
    dateCreated: string,
    author: string,
    content: string,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type UpdateNoteTypeMutationVariables = {
  input: UpdateNoteTypeInput,
  condition?: ModelNoteTypeConditionInput | null,
};

export type UpdateNoteTypeMutation = {
  updateNoteType?:  {
    __typename: "NoteType",
    id: string,
    requestID: string,
    dateCreated: string,
    author: string,
    content: string,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type DeleteNoteTypeMutationVariables = {
  input: DeleteNoteTypeInput,
  condition?: ModelNoteTypeConditionInput | null,
};

export type DeleteNoteTypeMutation = {
  deleteNoteType?:  {
    __typename: "NoteType",
    id: string,
    requestID: string,
    dateCreated: string,
    author: string,
    content: string,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type CreateSelfOrOtherInfoMutationVariables = {
  input: CreateSelfOrOtherInfoInput,
  condition?: ModelSelfOrOtherInfoConditionInput | null,
};

export type CreateSelfOrOtherInfoMutation = {
  createSelfOrOtherInfo?:  {
    __typename: "SelfOrOtherInfo",
    id: string,
    forSelf?: boolean | null,
    usedOtherResources?: boolean | null,
    otherResources?: string | null,
    requestFor?: string | null,
    requestIsKnown?: boolean | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type UpdateSelfOrOtherInfoMutationVariables = {
  input: UpdateSelfOrOtherInfoInput,
  condition?: ModelSelfOrOtherInfoConditionInput | null,
};

export type UpdateSelfOrOtherInfoMutation = {
  updateSelfOrOtherInfo?:  {
    __typename: "SelfOrOtherInfo",
    id: string,
    forSelf?: boolean | null,
    usedOtherResources?: boolean | null,
    otherResources?: string | null,
    requestFor?: string | null,
    requestIsKnown?: boolean | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type DeleteSelfOrOtherInfoMutationVariables = {
  input: DeleteSelfOrOtherInfoInput,
  condition?: ModelSelfOrOtherInfoConditionInput | null,
};

export type DeleteSelfOrOtherInfoMutation = {
  deleteSelfOrOtherInfo?:  {
    __typename: "SelfOrOtherInfo",
    id: string,
    forSelf?: boolean | null,
    usedOtherResources?: boolean | null,
    otherResources?: string | null,
    requestFor?: string | null,
    requestIsKnown?: boolean | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type CreateHouseholdItemsMutationVariables = {
  input: CreateHouseholdItemsInput,
  condition?: ModelHouseholdItemsConditionInput | null,
};

export type CreateHouseholdItemsMutation = {
  createHouseholdItems?:  {
    __typename: "HouseholdItems",
    id: string,
    shampoo?: boolean | null,
    bathSoap?: boolean | null,
    toothpaste?: boolean | null,
    toothbrush?: boolean | null,
    deodorant?: boolean | null,
    toiletPaper?: boolean | null,
    handSoap?: boolean | null,
    sanitaryPads?: boolean | null,
    tampons?: boolean | null,
    bleach?: boolean | null,
    lysolSpray?: boolean | null,
    lysolWipes?: boolean | null,
    dishsoap?: boolean | null,
    sponges?: boolean | null,
    pinesol?: boolean | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type UpdateHouseholdItemsMutationVariables = {
  input: UpdateHouseholdItemsInput,
  condition?: ModelHouseholdItemsConditionInput | null,
};

export type UpdateHouseholdItemsMutation = {
  updateHouseholdItems?:  {
    __typename: "HouseholdItems",
    id: string,
    shampoo?: boolean | null,
    bathSoap?: boolean | null,
    toothpaste?: boolean | null,
    toothbrush?: boolean | null,
    deodorant?: boolean | null,
    toiletPaper?: boolean | null,
    handSoap?: boolean | null,
    sanitaryPads?: boolean | null,
    tampons?: boolean | null,
    bleach?: boolean | null,
    lysolSpray?: boolean | null,
    lysolWipes?: boolean | null,
    dishsoap?: boolean | null,
    sponges?: boolean | null,
    pinesol?: boolean | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type DeleteHouseholdItemsMutationVariables = {
  input: DeleteHouseholdItemsInput,
  condition?: ModelHouseholdItemsConditionInput | null,
};

export type DeleteHouseholdItemsMutation = {
  deleteHouseholdItems?:  {
    __typename: "HouseholdItems",
    id: string,
    shampoo?: boolean | null,
    bathSoap?: boolean | null,
    toothpaste?: boolean | null,
    toothbrush?: boolean | null,
    deodorant?: boolean | null,
    toiletPaper?: boolean | null,
    handSoap?: boolean | null,
    sanitaryPads?: boolean | null,
    tampons?: boolean | null,
    bleach?: boolean | null,
    lysolSpray?: boolean | null,
    lysolWipes?: boolean | null,
    dishsoap?: boolean | null,
    sponges?: boolean | null,
    pinesol?: boolean | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type CreateFoodInfoMutationVariables = {
  input: CreateFoodInfoInput,
  condition?: ModelFoodInfoConditionInput | null,
};

export type CreateFoodInfoMutation = {
  createFoodInfo?:  {
    __typename: "FoodInfo",
    id: string,
    familyMembers?: number | null,
    children?: string | null,
    haveAllergies?: boolean | null,
    allergies?: string | null,
    milk?: boolean | null,
    eggs?: boolean | null,
    bread?: boolean | null,
    butter?: boolean | null,
    tortillas?: boolean | null,
    rice?: boolean | null,
    beans?: boolean | null,
    cheese?: boolean | null,
    beef?: boolean | null,
    hotdogs?: boolean | null,
    lunchMeat?: boolean | null,
    fruit?: boolean | null,
    peanutButter?: boolean | null,
    jelly?: boolean | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type UpdateFoodInfoMutationVariables = {
  input: UpdateFoodInfoInput,
  condition?: ModelFoodInfoConditionInput | null,
};

export type UpdateFoodInfoMutation = {
  updateFoodInfo?:  {
    __typename: "FoodInfo",
    id: string,
    familyMembers?: number | null,
    children?: string | null,
    haveAllergies?: boolean | null,
    allergies?: string | null,
    milk?: boolean | null,
    eggs?: boolean | null,
    bread?: boolean | null,
    butter?: boolean | null,
    tortillas?: boolean | null,
    rice?: boolean | null,
    beans?: boolean | null,
    cheese?: boolean | null,
    beef?: boolean | null,
    hotdogs?: boolean | null,
    lunchMeat?: boolean | null,
    fruit?: boolean | null,
    peanutButter?: boolean | null,
    jelly?: boolean | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type DeleteFoodInfoMutationVariables = {
  input: DeleteFoodInfoInput,
  condition?: ModelFoodInfoConditionInput | null,
};

export type DeleteFoodInfoMutation = {
  deleteFoodInfo?:  {
    __typename: "FoodInfo",
    id: string,
    familyMembers?: number | null,
    children?: string | null,
    haveAllergies?: boolean | null,
    allergies?: string | null,
    milk?: boolean | null,
    eggs?: boolean | null,
    bread?: boolean | null,
    butter?: boolean | null,
    tortillas?: boolean | null,
    rice?: boolean | null,
    beans?: boolean | null,
    cheese?: boolean | null,
    beef?: boolean | null,
    hotdogs?: boolean | null,
    lunchMeat?: boolean | null,
    fruit?: boolean | null,
    peanutButter?: boolean | null,
    jelly?: boolean | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type CreateMovingInfoMutationVariables = {
  input: CreateMovingInfoInput,
  condition?: ModelMovingInfoConditionInput | null,
};

export type CreateMovingInfoMutation = {
  createMovingInfo?:  {
    __typename: "MovingInfo",
    id: string,
    items?: string | null,
    haveTransportation?: boolean | null,
    steepDriveway?: boolean | null,
    stairs?: boolean | null,
    unpavedRoad?: boolean | null,
    other?: boolean | null,
    otherDetails?: string | null,
    liabilityAck?: boolean | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type UpdateMovingInfoMutationVariables = {
  input: UpdateMovingInfoInput,
  condition?: ModelMovingInfoConditionInput | null,
};

export type UpdateMovingInfoMutation = {
  updateMovingInfo?:  {
    __typename: "MovingInfo",
    id: string,
    items?: string | null,
    haveTransportation?: boolean | null,
    steepDriveway?: boolean | null,
    stairs?: boolean | null,
    unpavedRoad?: boolean | null,
    other?: boolean | null,
    otherDetails?: string | null,
    liabilityAck?: boolean | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type DeleteMovingInfoMutationVariables = {
  input: DeleteMovingInfoInput,
  condition?: ModelMovingInfoConditionInput | null,
};

export type DeleteMovingInfoMutation = {
  deleteMovingInfo?:  {
    __typename: "MovingInfo",
    id: string,
    items?: string | null,
    haveTransportation?: boolean | null,
    steepDriveway?: boolean | null,
    stairs?: boolean | null,
    unpavedRoad?: boolean | null,
    other?: boolean | null,
    otherDetails?: string | null,
    liabilityAck?: boolean | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type CreateHomeRepairTypeMutationVariables = {
  input: CreateHomeRepairTypeInput,
  condition?: ModelHomeRepairTypeConditionInput | null,
};

export type CreateHomeRepairTypeMutation = {
  createHomeRepairType?:  {
    __typename: "HomeRepairType",
    id: string,
    plumbing?: boolean | null,
    electrical?: boolean | null,
    painting?: boolean | null,
    yardwork?: boolean | null,
    other?: boolean | null,
    details?: string | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type UpdateHomeRepairTypeMutationVariables = {
  input: UpdateHomeRepairTypeInput,
  condition?: ModelHomeRepairTypeConditionInput | null,
};

export type UpdateHomeRepairTypeMutation = {
  updateHomeRepairType?:  {
    __typename: "HomeRepairType",
    id: string,
    plumbing?: boolean | null,
    electrical?: boolean | null,
    painting?: boolean | null,
    yardwork?: boolean | null,
    other?: boolean | null,
    details?: string | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type DeleteHomeRepairTypeMutationVariables = {
  input: DeleteHomeRepairTypeInput,
  condition?: ModelHomeRepairTypeConditionInput | null,
};

export type DeleteHomeRepairTypeMutation = {
  deleteHomeRepairType?:  {
    __typename: "HomeRepairType",
    id: string,
    plumbing?: boolean | null,
    electrical?: boolean | null,
    painting?: boolean | null,
    yardwork?: boolean | null,
    other?: boolean | null,
    details?: string | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type GetRequestQueryVariables = {
  id: string,
};

export type GetRequestQuery = {
  getRequest?:  {
    __typename: "Request",
    id: string,
    dateOfRequest: string,
    firstName: string,
    lastName: string,
    address?: string | null,
    city: string,
    zipCode?: number | null,
    phone?: string | null,
    email?: string | null,
    spanishOnly?: boolean | null,
    preferredContactTime?: string | null,
    request?: string | null,
    leadSource: LeadSource,
    leadOtherDetails?: string | null,
    selfOrOtherInfo:  {
      __typename: "SelfOrOtherInfo",
      id: string,
      forSelf?: boolean | null,
      usedOtherResources?: boolean | null,
      otherResources?: string | null,
      requestFor?: string | null,
      requestIsKnown?: boolean | null,
      createdAt: string,
      updatedAt: string,
    },
    foodRequest?:  {
      __typename: "FoodInfo",
      id: string,
      familyMembers?: number | null,
      children?: string | null,
      haveAllergies?: boolean | null,
      allergies?: string | null,
      milk?: boolean | null,
      eggs?: boolean | null,
      bread?: boolean | null,
      butter?: boolean | null,
      tortillas?: boolean | null,
      rice?: boolean | null,
      beans?: boolean | null,
      cheese?: boolean | null,
      beef?: boolean | null,
      hotdogs?: boolean | null,
      lunchMeat?: boolean | null,
      fruit?: boolean | null,
      peanutButter?: boolean | null,
      jelly?: boolean | null,
      createdAt: string,
      updatedAt: string,
    } | null,
    movingRequest?:  {
      __typename: "MovingInfo",
      id: string,
      items?: string | null,
      haveTransportation?: boolean | null,
      steepDriveway?: boolean | null,
      stairs?: boolean | null,
      unpavedRoad?: boolean | null,
      other?: boolean | null,
      otherDetails?: string | null,
      liabilityAck?: boolean | null,
      createdAt: string,
      updatedAt: string,
    } | null,
    resumeHelp?: boolean | null,
    coverLetterHelp?: boolean | null,
    carRepairDetails?: string | null,
    homeRepairType?:  {
      __typename: "HomeRepairType",
      id: string,
      plumbing?: boolean | null,
      electrical?: boolean | null,
      painting?: boolean | null,
      yardwork?: boolean | null,
      other?: boolean | null,
      details?: string | null,
      createdAt: string,
      updatedAt: string,
    } | null,
    clothingType?: string | null,
    clothingSize?: string | null,
    furnitureType?: string | null,
    housingHelp?: boolean | null,
    householdItems?:  {
      __typename: "HouseholdItems",
      id: string,
      shampoo?: boolean | null,
      bathSoap?: boolean | null,
      toothpaste?: boolean | null,
      toothbrush?: boolean | null,
      deodorant?: boolean | null,
      toiletPaper?: boolean | null,
      handSoap?: boolean | null,
      sanitaryPads?: boolean | null,
      tampons?: boolean | null,
      bleach?: boolean | null,
      lysolSpray?: boolean | null,
      lysolWipes?: boolean | null,
      dishsoap?: boolean | null,
      sponges?: boolean | null,
      pinesol?: boolean | null,
      createdAt: string,
      updatedAt: string,
    } | null,
    needReason: Array< NeedReason | null >,
    needTypes: Array< NeedType | null >,
    status: RequestStatus,
    note?:  {
      __typename: "ModelNoteTypeConnection",
      items:  Array< {
        __typename: "NoteType",
        id: string,
        requestID: string,
        dateCreated: string,
        author: string,
        content: string,
        createdAt: string,
        updatedAt: string,
      } | null >,
      nextToken?: string | null,
    } | null,
    otherNeeds?: string | null,
    needFulfiller?: string | null,
    dateFulfilled?: string | null,
    followUp?: string | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type ListRequestsQueryVariables = {
  filter?: ModelRequestFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ListRequestsQuery = {
  listRequests?:  {
    __typename: "ModelRequestConnection",
    items:  Array< {
      __typename: "Request",
      id: string,
      dateOfRequest: string,
      firstName: string,
      lastName: string,
      address?: string | null,
      city: string,
      zipCode?: number | null,
      phone?: string | null,
      email?: string | null,
      spanishOnly?: boolean | null,
      preferredContactTime?: string | null,
      request?: string | null,
      leadSource: LeadSource,
      leadOtherDetails?: string | null,
      selfOrOtherInfo:  {
        __typename: "SelfOrOtherInfo",
        id: string,
        forSelf?: boolean | null,
        usedOtherResources?: boolean | null,
        otherResources?: string | null,
        requestFor?: string | null,
        requestIsKnown?: boolean | null,
        createdAt: string,
        updatedAt: string,
      },
      foodRequest?:  {
        __typename: "FoodInfo",
        id: string,
        familyMembers?: number | null,
        children?: string | null,
        haveAllergies?: boolean | null,
        allergies?: string | null,
        milk?: boolean | null,
        eggs?: boolean | null,
        bread?: boolean | null,
        butter?: boolean | null,
        tortillas?: boolean | null,
        rice?: boolean | null,
        beans?: boolean | null,
        cheese?: boolean | null,
        beef?: boolean | null,
        hotdogs?: boolean | null,
        lunchMeat?: boolean | null,
        fruit?: boolean | null,
        peanutButter?: boolean | null,
        jelly?: boolean | null,
        createdAt: string,
        updatedAt: string,
      } | null,
      movingRequest?:  {
        __typename: "MovingInfo",
        id: string,
        items?: string | null,
        haveTransportation?: boolean | null,
        steepDriveway?: boolean | null,
        stairs?: boolean | null,
        unpavedRoad?: boolean | null,
        other?: boolean | null,
        otherDetails?: string | null,
        liabilityAck?: boolean | null,
        createdAt: string,
        updatedAt: string,
      } | null,
      resumeHelp?: boolean | null,
      coverLetterHelp?: boolean | null,
      carRepairDetails?: string | null,
      homeRepairType?:  {
        __typename: "HomeRepairType",
        id: string,
        plumbing?: boolean | null,
        electrical?: boolean | null,
        painting?: boolean | null,
        yardwork?: boolean | null,
        other?: boolean | null,
        details?: string | null,
        createdAt: string,
        updatedAt: string,
      } | null,
      clothingType?: string | null,
      clothingSize?: string | null,
      furnitureType?: string | null,
      housingHelp?: boolean | null,
      householdItems?:  {
        __typename: "HouseholdItems",
        id: string,
        shampoo?: boolean | null,
        bathSoap?: boolean | null,
        toothpaste?: boolean | null,
        toothbrush?: boolean | null,
        deodorant?: boolean | null,
        toiletPaper?: boolean | null,
        handSoap?: boolean | null,
        sanitaryPads?: boolean | null,
        tampons?: boolean | null,
        bleach?: boolean | null,
        lysolSpray?: boolean | null,
        lysolWipes?: boolean | null,
        dishsoap?: boolean | null,
        sponges?: boolean | null,
        pinesol?: boolean | null,
        createdAt: string,
        updatedAt: string,
      } | null,
      needReason: Array< NeedReason | null >,
      needTypes: Array< NeedType | null >,
      status: RequestStatus,
      note?:  {
        __typename: "ModelNoteTypeConnection",
        items:  Array< {
          __typename: "NoteType",
          id: string,
          requestID: string,
          dateCreated: string,
          author: string,
          content: string,
          createdAt: string,
          updatedAt: string,
        } | null >,
        nextToken?: string | null,
      } | null,
      otherNeeds?: string | null,
      needFulfiller?: string | null,
      dateFulfilled?: string | null,
      followUp?: string | null,
      createdAt: string,
      updatedAt: string,
    } | null >,
    nextToken?: string | null,
  } | null,
};

export type GetNoteTypeQueryVariables = {
  id: string,
};

export type GetNoteTypeQuery = {
  getNoteType?:  {
    __typename: "NoteType",
    id: string,
    requestID: string,
    dateCreated: string,
    author: string,
    content: string,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type ListNoteTypesQueryVariables = {
  filter?: ModelNoteTypeFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ListNoteTypesQuery = {
  listNoteTypes?:  {
    __typename: "ModelNoteTypeConnection",
    items:  Array< {
      __typename: "NoteType",
      id: string,
      requestID: string,
      dateCreated: string,
      author: string,
      content: string,
      createdAt: string,
      updatedAt: string,
    } | null >,
    nextToken?: string | null,
  } | null,
};

export type GetSelfOrOtherInfoQueryVariables = {
  id: string,
};

export type GetSelfOrOtherInfoQuery = {
  getSelfOrOtherInfo?:  {
    __typename: "SelfOrOtherInfo",
    id: string,
    forSelf?: boolean | null,
    usedOtherResources?: boolean | null,
    otherResources?: string | null,
    requestFor?: string | null,
    requestIsKnown?: boolean | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type ListSelfOrOtherInfosQueryVariables = {
  filter?: ModelSelfOrOtherInfoFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ListSelfOrOtherInfosQuery = {
  listSelfOrOtherInfos?:  {
    __typename: "ModelSelfOrOtherInfoConnection",
    items:  Array< {
      __typename: "SelfOrOtherInfo",
      id: string,
      forSelf?: boolean | null,
      usedOtherResources?: boolean | null,
      otherResources?: string | null,
      requestFor?: string | null,
      requestIsKnown?: boolean | null,
      createdAt: string,
      updatedAt: string,
    } | null >,
    nextToken?: string | null,
  } | null,
};

export type GetHouseholdItemsQueryVariables = {
  id: string,
};

export type GetHouseholdItemsQuery = {
  getHouseholdItems?:  {
    __typename: "HouseholdItems",
    id: string,
    shampoo?: boolean | null,
    bathSoap?: boolean | null,
    toothpaste?: boolean | null,
    toothbrush?: boolean | null,
    deodorant?: boolean | null,
    toiletPaper?: boolean | null,
    handSoap?: boolean | null,
    sanitaryPads?: boolean | null,
    tampons?: boolean | null,
    bleach?: boolean | null,
    lysolSpray?: boolean | null,
    lysolWipes?: boolean | null,
    dishsoap?: boolean | null,
    sponges?: boolean | null,
    pinesol?: boolean | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type ListHouseholdItemssQueryVariables = {
  filter?: ModelHouseholdItemsFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ListHouseholdItemssQuery = {
  listHouseholdItemss?:  {
    __typename: "ModelHouseholdItemsConnection",
    items:  Array< {
      __typename: "HouseholdItems",
      id: string,
      shampoo?: boolean | null,
      bathSoap?: boolean | null,
      toothpaste?: boolean | null,
      toothbrush?: boolean | null,
      deodorant?: boolean | null,
      toiletPaper?: boolean | null,
      handSoap?: boolean | null,
      sanitaryPads?: boolean | null,
      tampons?: boolean | null,
      bleach?: boolean | null,
      lysolSpray?: boolean | null,
      lysolWipes?: boolean | null,
      dishsoap?: boolean | null,
      sponges?: boolean | null,
      pinesol?: boolean | null,
      createdAt: string,
      updatedAt: string,
    } | null >,
    nextToken?: string | null,
  } | null,
};

export type GetFoodInfoQueryVariables = {
  id: string,
};

export type GetFoodInfoQuery = {
  getFoodInfo?:  {
    __typename: "FoodInfo",
    id: string,
    familyMembers?: number | null,
    children?: string | null,
    haveAllergies?: boolean | null,
    allergies?: string | null,
    milk?: boolean | null,
    eggs?: boolean | null,
    bread?: boolean | null,
    butter?: boolean | null,
    tortillas?: boolean | null,
    rice?: boolean | null,
    beans?: boolean | null,
    cheese?: boolean | null,
    beef?: boolean | null,
    hotdogs?: boolean | null,
    lunchMeat?: boolean | null,
    fruit?: boolean | null,
    peanutButter?: boolean | null,
    jelly?: boolean | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type ListFoodInfosQueryVariables = {
  filter?: ModelFoodInfoFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ListFoodInfosQuery = {
  listFoodInfos?:  {
    __typename: "ModelFoodInfoConnection",
    items:  Array< {
      __typename: "FoodInfo",
      id: string,
      familyMembers?: number | null,
      children?: string | null,
      haveAllergies?: boolean | null,
      allergies?: string | null,
      milk?: boolean | null,
      eggs?: boolean | null,
      bread?: boolean | null,
      butter?: boolean | null,
      tortillas?: boolean | null,
      rice?: boolean | null,
      beans?: boolean | null,
      cheese?: boolean | null,
      beef?: boolean | null,
      hotdogs?: boolean | null,
      lunchMeat?: boolean | null,
      fruit?: boolean | null,
      peanutButter?: boolean | null,
      jelly?: boolean | null,
      createdAt: string,
      updatedAt: string,
    } | null >,
    nextToken?: string | null,
  } | null,
};

export type GetMovingInfoQueryVariables = {
  id: string,
};

export type GetMovingInfoQuery = {
  getMovingInfo?:  {
    __typename: "MovingInfo",
    id: string,
    items?: string | null,
    haveTransportation?: boolean | null,
    steepDriveway?: boolean | null,
    stairs?: boolean | null,
    unpavedRoad?: boolean | null,
    other?: boolean | null,
    otherDetails?: string | null,
    liabilityAck?: boolean | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type ListMovingInfosQueryVariables = {
  filter?: ModelMovingInfoFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ListMovingInfosQuery = {
  listMovingInfos?:  {
    __typename: "ModelMovingInfoConnection",
    items:  Array< {
      __typename: "MovingInfo",
      id: string,
      items?: string | null,
      haveTransportation?: boolean | null,
      steepDriveway?: boolean | null,
      stairs?: boolean | null,
      unpavedRoad?: boolean | null,
      other?: boolean | null,
      otherDetails?: string | null,
      liabilityAck?: boolean | null,
      createdAt: string,
      updatedAt: string,
    } | null >,
    nextToken?: string | null,
  } | null,
};

export type GetHomeRepairTypeQueryVariables = {
  id: string,
};

export type GetHomeRepairTypeQuery = {
  getHomeRepairType?:  {
    __typename: "HomeRepairType",
    id: string,
    plumbing?: boolean | null,
    electrical?: boolean | null,
    painting?: boolean | null,
    yardwork?: boolean | null,
    other?: boolean | null,
    details?: string | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type ListHomeRepairTypesQueryVariables = {
  filter?: ModelHomeRepairTypeFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ListHomeRepairTypesQuery = {
  listHomeRepairTypes?:  {
    __typename: "ModelHomeRepairTypeConnection",
    items:  Array< {
      __typename: "HomeRepairType",
      id: string,
      plumbing?: boolean | null,
      electrical?: boolean | null,
      painting?: boolean | null,
      yardwork?: boolean | null,
      other?: boolean | null,
      details?: string | null,
      createdAt: string,
      updatedAt: string,
    } | null >,
    nextToken?: string | null,
  } | null,
};

export type OnCreateRequestSubscription = {
  onCreateRequest?:  {
    __typename: "Request",
    id: string,
    dateOfRequest: string,
    firstName: string,
    lastName: string,
    address?: string | null,
    city: string,
    zipCode?: number | null,
    phone?: string | null,
    email?: string | null,
    spanishOnly?: boolean | null,
    preferredContactTime?: string | null,
    request?: string | null,
    leadSource: LeadSource,
    leadOtherDetails?: string | null,
    selfOrOtherInfo:  {
      __typename: "SelfOrOtherInfo",
      id: string,
      forSelf?: boolean | null,
      usedOtherResources?: boolean | null,
      otherResources?: string | null,
      requestFor?: string | null,
      requestIsKnown?: boolean | null,
      createdAt: string,
      updatedAt: string,
    },
    foodRequest?:  {
      __typename: "FoodInfo",
      id: string,
      familyMembers?: number | null,
      children?: string | null,
      haveAllergies?: boolean | null,
      allergies?: string | null,
      milk?: boolean | null,
      eggs?: boolean | null,
      bread?: boolean | null,
      butter?: boolean | null,
      tortillas?: boolean | null,
      rice?: boolean | null,
      beans?: boolean | null,
      cheese?: boolean | null,
      beef?: boolean | null,
      hotdogs?: boolean | null,
      lunchMeat?: boolean | null,
      fruit?: boolean | null,
      peanutButter?: boolean | null,
      jelly?: boolean | null,
      createdAt: string,
      updatedAt: string,
    } | null,
    movingRequest?:  {
      __typename: "MovingInfo",
      id: string,
      items?: string | null,
      haveTransportation?: boolean | null,
      steepDriveway?: boolean | null,
      stairs?: boolean | null,
      unpavedRoad?: boolean | null,
      other?: boolean | null,
      otherDetails?: string | null,
      liabilityAck?: boolean | null,
      createdAt: string,
      updatedAt: string,
    } | null,
    resumeHelp?: boolean | null,
    coverLetterHelp?: boolean | null,
    carRepairDetails?: string | null,
    homeRepairType?:  {
      __typename: "HomeRepairType",
      id: string,
      plumbing?: boolean | null,
      electrical?: boolean | null,
      painting?: boolean | null,
      yardwork?: boolean | null,
      other?: boolean | null,
      details?: string | null,
      createdAt: string,
      updatedAt: string,
    } | null,
    clothingType?: string | null,
    clothingSize?: string | null,
    furnitureType?: string | null,
    housingHelp?: boolean | null,
    householdItems?:  {
      __typename: "HouseholdItems",
      id: string,
      shampoo?: boolean | null,
      bathSoap?: boolean | null,
      toothpaste?: boolean | null,
      toothbrush?: boolean | null,
      deodorant?: boolean | null,
      toiletPaper?: boolean | null,
      handSoap?: boolean | null,
      sanitaryPads?: boolean | null,
      tampons?: boolean | null,
      bleach?: boolean | null,
      lysolSpray?: boolean | null,
      lysolWipes?: boolean | null,
      dishsoap?: boolean | null,
      sponges?: boolean | null,
      pinesol?: boolean | null,
      createdAt: string,
      updatedAt: string,
    } | null,
    needReason: Array< NeedReason | null >,
    needTypes: Array< NeedType | null >,
    status: RequestStatus,
    note?:  {
      __typename: "ModelNoteTypeConnection",
      items:  Array< {
        __typename: "NoteType",
        id: string,
        requestID: string,
        dateCreated: string,
        author: string,
        content: string,
        createdAt: string,
        updatedAt: string,
      } | null >,
      nextToken?: string | null,
    } | null,
    otherNeeds?: string | null,
    needFulfiller?: string | null,
    dateFulfilled?: string | null,
    followUp?: string | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnUpdateRequestSubscription = {
  onUpdateRequest?:  {
    __typename: "Request",
    id: string,
    dateOfRequest: string,
    firstName: string,
    lastName: string,
    address?: string | null,
    city: string,
    zipCode?: number | null,
    phone?: string | null,
    email?: string | null,
    spanishOnly?: boolean | null,
    preferredContactTime?: string | null,
    request?: string | null,
    leadSource: LeadSource,
    leadOtherDetails?: string | null,
    selfOrOtherInfo:  {
      __typename: "SelfOrOtherInfo",
      id: string,
      forSelf?: boolean | null,
      usedOtherResources?: boolean | null,
      otherResources?: string | null,
      requestFor?: string | null,
      requestIsKnown?: boolean | null,
      createdAt: string,
      updatedAt: string,
    },
    foodRequest?:  {
      __typename: "FoodInfo",
      id: string,
      familyMembers?: number | null,
      children?: string | null,
      haveAllergies?: boolean | null,
      allergies?: string | null,
      milk?: boolean | null,
      eggs?: boolean | null,
      bread?: boolean | null,
      butter?: boolean | null,
      tortillas?: boolean | null,
      rice?: boolean | null,
      beans?: boolean | null,
      cheese?: boolean | null,
      beef?: boolean | null,
      hotdogs?: boolean | null,
      lunchMeat?: boolean | null,
      fruit?: boolean | null,
      peanutButter?: boolean | null,
      jelly?: boolean | null,
      createdAt: string,
      updatedAt: string,
    } | null,
    movingRequest?:  {
      __typename: "MovingInfo",
      id: string,
      items?: string | null,
      haveTransportation?: boolean | null,
      steepDriveway?: boolean | null,
      stairs?: boolean | null,
      unpavedRoad?: boolean | null,
      other?: boolean | null,
      otherDetails?: string | null,
      liabilityAck?: boolean | null,
      createdAt: string,
      updatedAt: string,
    } | null,
    resumeHelp?: boolean | null,
    coverLetterHelp?: boolean | null,
    carRepairDetails?: string | null,
    homeRepairType?:  {
      __typename: "HomeRepairType",
      id: string,
      plumbing?: boolean | null,
      electrical?: boolean | null,
      painting?: boolean | null,
      yardwork?: boolean | null,
      other?: boolean | null,
      details?: string | null,
      createdAt: string,
      updatedAt: string,
    } | null,
    clothingType?: string | null,
    clothingSize?: string | null,
    furnitureType?: string | null,
    housingHelp?: boolean | null,
    householdItems?:  {
      __typename: "HouseholdItems",
      id: string,
      shampoo?: boolean | null,
      bathSoap?: boolean | null,
      toothpaste?: boolean | null,
      toothbrush?: boolean | null,
      deodorant?: boolean | null,
      toiletPaper?: boolean | null,
      handSoap?: boolean | null,
      sanitaryPads?: boolean | null,
      tampons?: boolean | null,
      bleach?: boolean | null,
      lysolSpray?: boolean | null,
      lysolWipes?: boolean | null,
      dishsoap?: boolean | null,
      sponges?: boolean | null,
      pinesol?: boolean | null,
      createdAt: string,
      updatedAt: string,
    } | null,
    needReason: Array< NeedReason | null >,
    needTypes: Array< NeedType | null >,
    status: RequestStatus,
    note?:  {
      __typename: "ModelNoteTypeConnection",
      items:  Array< {
        __typename: "NoteType",
        id: string,
        requestID: string,
        dateCreated: string,
        author: string,
        content: string,
        createdAt: string,
        updatedAt: string,
      } | null >,
      nextToken?: string | null,
    } | null,
    otherNeeds?: string | null,
    needFulfiller?: string | null,
    dateFulfilled?: string | null,
    followUp?: string | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnDeleteRequestSubscription = {
  onDeleteRequest?:  {
    __typename: "Request",
    id: string,
    dateOfRequest: string,
    firstName: string,
    lastName: string,
    address?: string | null,
    city: string,
    zipCode?: number | null,
    phone?: string | null,
    email?: string | null,
    spanishOnly?: boolean | null,
    preferredContactTime?: string | null,
    request?: string | null,
    leadSource: LeadSource,
    leadOtherDetails?: string | null,
    selfOrOtherInfo:  {
      __typename: "SelfOrOtherInfo",
      id: string,
      forSelf?: boolean | null,
      usedOtherResources?: boolean | null,
      otherResources?: string | null,
      requestFor?: string | null,
      requestIsKnown?: boolean | null,
      createdAt: string,
      updatedAt: string,
    },
    foodRequest?:  {
      __typename: "FoodInfo",
      id: string,
      familyMembers?: number | null,
      children?: string | null,
      haveAllergies?: boolean | null,
      allergies?: string | null,
      milk?: boolean | null,
      eggs?: boolean | null,
      bread?: boolean | null,
      butter?: boolean | null,
      tortillas?: boolean | null,
      rice?: boolean | null,
      beans?: boolean | null,
      cheese?: boolean | null,
      beef?: boolean | null,
      hotdogs?: boolean | null,
      lunchMeat?: boolean | null,
      fruit?: boolean | null,
      peanutButter?: boolean | null,
      jelly?: boolean | null,
      createdAt: string,
      updatedAt: string,
    } | null,
    movingRequest?:  {
      __typename: "MovingInfo",
      id: string,
      items?: string | null,
      haveTransportation?: boolean | null,
      steepDriveway?: boolean | null,
      stairs?: boolean | null,
      unpavedRoad?: boolean | null,
      other?: boolean | null,
      otherDetails?: string | null,
      liabilityAck?: boolean | null,
      createdAt: string,
      updatedAt: string,
    } | null,
    resumeHelp?: boolean | null,
    coverLetterHelp?: boolean | null,
    carRepairDetails?: string | null,
    homeRepairType?:  {
      __typename: "HomeRepairType",
      id: string,
      plumbing?: boolean | null,
      electrical?: boolean | null,
      painting?: boolean | null,
      yardwork?: boolean | null,
      other?: boolean | null,
      details?: string | null,
      createdAt: string,
      updatedAt: string,
    } | null,
    clothingType?: string | null,
    clothingSize?: string | null,
    furnitureType?: string | null,
    housingHelp?: boolean | null,
    householdItems?:  {
      __typename: "HouseholdItems",
      id: string,
      shampoo?: boolean | null,
      bathSoap?: boolean | null,
      toothpaste?: boolean | null,
      toothbrush?: boolean | null,
      deodorant?: boolean | null,
      toiletPaper?: boolean | null,
      handSoap?: boolean | null,
      sanitaryPads?: boolean | null,
      tampons?: boolean | null,
      bleach?: boolean | null,
      lysolSpray?: boolean | null,
      lysolWipes?: boolean | null,
      dishsoap?: boolean | null,
      sponges?: boolean | null,
      pinesol?: boolean | null,
      createdAt: string,
      updatedAt: string,
    } | null,
    needReason: Array< NeedReason | null >,
    needTypes: Array< NeedType | null >,
    status: RequestStatus,
    note?:  {
      __typename: "ModelNoteTypeConnection",
      items:  Array< {
        __typename: "NoteType",
        id: string,
        requestID: string,
        dateCreated: string,
        author: string,
        content: string,
        createdAt: string,
        updatedAt: string,
      } | null >,
      nextToken?: string | null,
    } | null,
    otherNeeds?: string | null,
    needFulfiller?: string | null,
    dateFulfilled?: string | null,
    followUp?: string | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnCreateNoteTypeSubscription = {
  onCreateNoteType?:  {
    __typename: "NoteType",
    id: string,
    requestID: string,
    dateCreated: string,
    author: string,
    content: string,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnUpdateNoteTypeSubscription = {
  onUpdateNoteType?:  {
    __typename: "NoteType",
    id: string,
    requestID: string,
    dateCreated: string,
    author: string,
    content: string,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnDeleteNoteTypeSubscription = {
  onDeleteNoteType?:  {
    __typename: "NoteType",
    id: string,
    requestID: string,
    dateCreated: string,
    author: string,
    content: string,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnCreateSelfOrOtherInfoSubscription = {
  onCreateSelfOrOtherInfo?:  {
    __typename: "SelfOrOtherInfo",
    id: string,
    forSelf?: boolean | null,
    usedOtherResources?: boolean | null,
    otherResources?: string | null,
    requestFor?: string | null,
    requestIsKnown?: boolean | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnUpdateSelfOrOtherInfoSubscription = {
  onUpdateSelfOrOtherInfo?:  {
    __typename: "SelfOrOtherInfo",
    id: string,
    forSelf?: boolean | null,
    usedOtherResources?: boolean | null,
    otherResources?: string | null,
    requestFor?: string | null,
    requestIsKnown?: boolean | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnDeleteSelfOrOtherInfoSubscription = {
  onDeleteSelfOrOtherInfo?:  {
    __typename: "SelfOrOtherInfo",
    id: string,
    forSelf?: boolean | null,
    usedOtherResources?: boolean | null,
    otherResources?: string | null,
    requestFor?: string | null,
    requestIsKnown?: boolean | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnCreateHouseholdItemsSubscription = {
  onCreateHouseholdItems?:  {
    __typename: "HouseholdItems",
    id: string,
    shampoo?: boolean | null,
    bathSoap?: boolean | null,
    toothpaste?: boolean | null,
    toothbrush?: boolean | null,
    deodorant?: boolean | null,
    toiletPaper?: boolean | null,
    handSoap?: boolean | null,
    sanitaryPads?: boolean | null,
    tampons?: boolean | null,
    bleach?: boolean | null,
    lysolSpray?: boolean | null,
    lysolWipes?: boolean | null,
    dishsoap?: boolean | null,
    sponges?: boolean | null,
    pinesol?: boolean | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnUpdateHouseholdItemsSubscription = {
  onUpdateHouseholdItems?:  {
    __typename: "HouseholdItems",
    id: string,
    shampoo?: boolean | null,
    bathSoap?: boolean | null,
    toothpaste?: boolean | null,
    toothbrush?: boolean | null,
    deodorant?: boolean | null,
    toiletPaper?: boolean | null,
    handSoap?: boolean | null,
    sanitaryPads?: boolean | null,
    tampons?: boolean | null,
    bleach?: boolean | null,
    lysolSpray?: boolean | null,
    lysolWipes?: boolean | null,
    dishsoap?: boolean | null,
    sponges?: boolean | null,
    pinesol?: boolean | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnDeleteHouseholdItemsSubscription = {
  onDeleteHouseholdItems?:  {
    __typename: "HouseholdItems",
    id: string,
    shampoo?: boolean | null,
    bathSoap?: boolean | null,
    toothpaste?: boolean | null,
    toothbrush?: boolean | null,
    deodorant?: boolean | null,
    toiletPaper?: boolean | null,
    handSoap?: boolean | null,
    sanitaryPads?: boolean | null,
    tampons?: boolean | null,
    bleach?: boolean | null,
    lysolSpray?: boolean | null,
    lysolWipes?: boolean | null,
    dishsoap?: boolean | null,
    sponges?: boolean | null,
    pinesol?: boolean | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnCreateFoodInfoSubscription = {
  onCreateFoodInfo?:  {
    __typename: "FoodInfo",
    id: string,
    familyMembers?: number | null,
    children?: string | null,
    haveAllergies?: boolean | null,
    allergies?: string | null,
    milk?: boolean | null,
    eggs?: boolean | null,
    bread?: boolean | null,
    butter?: boolean | null,
    tortillas?: boolean | null,
    rice?: boolean | null,
    beans?: boolean | null,
    cheese?: boolean | null,
    beef?: boolean | null,
    hotdogs?: boolean | null,
    lunchMeat?: boolean | null,
    fruit?: boolean | null,
    peanutButter?: boolean | null,
    jelly?: boolean | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnUpdateFoodInfoSubscription = {
  onUpdateFoodInfo?:  {
    __typename: "FoodInfo",
    id: string,
    familyMembers?: number | null,
    children?: string | null,
    haveAllergies?: boolean | null,
    allergies?: string | null,
    milk?: boolean | null,
    eggs?: boolean | null,
    bread?: boolean | null,
    butter?: boolean | null,
    tortillas?: boolean | null,
    rice?: boolean | null,
    beans?: boolean | null,
    cheese?: boolean | null,
    beef?: boolean | null,
    hotdogs?: boolean | null,
    lunchMeat?: boolean | null,
    fruit?: boolean | null,
    peanutButter?: boolean | null,
    jelly?: boolean | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnDeleteFoodInfoSubscription = {
  onDeleteFoodInfo?:  {
    __typename: "FoodInfo",
    id: string,
    familyMembers?: number | null,
    children?: string | null,
    haveAllergies?: boolean | null,
    allergies?: string | null,
    milk?: boolean | null,
    eggs?: boolean | null,
    bread?: boolean | null,
    butter?: boolean | null,
    tortillas?: boolean | null,
    rice?: boolean | null,
    beans?: boolean | null,
    cheese?: boolean | null,
    beef?: boolean | null,
    hotdogs?: boolean | null,
    lunchMeat?: boolean | null,
    fruit?: boolean | null,
    peanutButter?: boolean | null,
    jelly?: boolean | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnCreateMovingInfoSubscription = {
  onCreateMovingInfo?:  {
    __typename: "MovingInfo",
    id: string,
    items?: string | null,
    haveTransportation?: boolean | null,
    steepDriveway?: boolean | null,
    stairs?: boolean | null,
    unpavedRoad?: boolean | null,
    other?: boolean | null,
    otherDetails?: string | null,
    liabilityAck?: boolean | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnUpdateMovingInfoSubscription = {
  onUpdateMovingInfo?:  {
    __typename: "MovingInfo",
    id: string,
    items?: string | null,
    haveTransportation?: boolean | null,
    steepDriveway?: boolean | null,
    stairs?: boolean | null,
    unpavedRoad?: boolean | null,
    other?: boolean | null,
    otherDetails?: string | null,
    liabilityAck?: boolean | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnDeleteMovingInfoSubscription = {
  onDeleteMovingInfo?:  {
    __typename: "MovingInfo",
    id: string,
    items?: string | null,
    haveTransportation?: boolean | null,
    steepDriveway?: boolean | null,
    stairs?: boolean | null,
    unpavedRoad?: boolean | null,
    other?: boolean | null,
    otherDetails?: string | null,
    liabilityAck?: boolean | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnCreateHomeRepairTypeSubscription = {
  onCreateHomeRepairType?:  {
    __typename: "HomeRepairType",
    id: string,
    plumbing?: boolean | null,
    electrical?: boolean | null,
    painting?: boolean | null,
    yardwork?: boolean | null,
    other?: boolean | null,
    details?: string | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnUpdateHomeRepairTypeSubscription = {
  onUpdateHomeRepairType?:  {
    __typename: "HomeRepairType",
    id: string,
    plumbing?: boolean | null,
    electrical?: boolean | null,
    painting?: boolean | null,
    yardwork?: boolean | null,
    other?: boolean | null,
    details?: string | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};

export type OnDeleteHomeRepairTypeSubscription = {
  onDeleteHomeRepairType?:  {
    __typename: "HomeRepairType",
    id: string,
    plumbing?: boolean | null,
    electrical?: boolean | null,
    painting?: boolean | null,
    yardwork?: boolean | null,
    other?: boolean | null,
    details?: string | null,
    createdAt: string,
    updatedAt: string,
  } | null,
};
